#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="valija")]
public partial class DataValijaDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public DataValijaDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["valijaConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataValijaDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataValijaDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataValijaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataValijaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_cabValija> tbl_cabValija
	{
		get
		{
			return this.GetTable<tbl_cabValija>();
		}
	}
	
	public System.Data.Linq.Table<tbl_detValija> tbl_detValija
	{
		get
		{
			return this.GetTable<tbl_detValija>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_cabValija")]
public partial class tbl_cabValija
{
	
	private int _id_cabValija;
	
	private string _sucOrigen;
	
	private string _numero;
	
	private System.Nullable<System.DateTime> _fechaEnvio;
	
	private System.Nullable<System.DateTime> _fechaRecepcion;
	
	private System.Nullable<System.DateTime> _fechaCreacion;
	
	private string _cedulaEmisor;
	
	private string _cedulaReceptor;
	
	private string _usuario;
	
	private System.Nullable<bool> _enviado;
	
	private System.Nullable<bool> _recibido;
	
	private System.Nullable<bool> _ingresa;
	
	private System.Nullable<bool> _despacha;
	
	public tbl_cabValija()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cabValija", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id_cabValija
	{
		get
		{
			return this._id_cabValija;
		}
		set
		{
			if ((this._id_cabValija != value))
			{
				this._id_cabValija = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sucOrigen", DbType="NChar(3)")]
	public string sucOrigen
	{
		get
		{
			return this._sucOrigen;
		}
		set
		{
			if ((this._sucOrigen != value))
			{
				this._sucOrigen = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numero", DbType="NChar(13)")]
	public string numero
	{
		get
		{
			return this._numero;
		}
		set
		{
			if ((this._numero != value))
			{
				this._numero = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEnvio", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaEnvio
	{
		get
		{
			return this._fechaEnvio;
		}
		set
		{
			if ((this._fechaEnvio != value))
			{
				this._fechaEnvio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaRecepcion", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaRecepcion
	{
		get
		{
			return this._fechaRecepcion;
		}
		set
		{
			if ((this._fechaRecepcion != value))
			{
				this._fechaRecepcion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaCreacion", DbType="DateTime")]
	public System.Nullable<System.DateTime> fechaCreacion
	{
		get
		{
			return this._fechaCreacion;
		}
		set
		{
			if ((this._fechaCreacion != value))
			{
				this._fechaCreacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaEmisor", DbType="NChar(16)")]
	public string cedulaEmisor
	{
		get
		{
			return this._cedulaEmisor;
		}
		set
		{
			if ((this._cedulaEmisor != value))
			{
				this._cedulaEmisor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaReceptor", DbType="NChar(16)")]
	public string cedulaReceptor
	{
		get
		{
			return this._cedulaReceptor;
		}
		set
		{
			if ((this._cedulaReceptor != value))
			{
				this._cedulaReceptor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="NChar(25)")]
	public string usuario
	{
		get
		{
			return this._usuario;
		}
		set
		{
			if ((this._usuario != value))
			{
				this._usuario = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enviado", DbType="Bit")]
	public System.Nullable<bool> enviado
	{
		get
		{
			return this._enviado;
		}
		set
		{
			if ((this._enviado != value))
			{
				this._enviado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recibido", DbType="Bit")]
	public System.Nullable<bool> recibido
	{
		get
		{
			return this._recibido;
		}
		set
		{
			if ((this._recibido != value))
			{
				this._recibido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingresa", DbType="Bit")]
	public System.Nullable<bool> ingresa
	{
		get
		{
			return this._ingresa;
		}
		set
		{
			if ((this._ingresa != value))
			{
				this._ingresa = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_despacha", DbType="Bit")]
	public System.Nullable<bool> despacha
	{
		get
		{
			return this._despacha;
		}
		set
		{
			if ((this._despacha != value))
			{
				this._despacha = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_detValija")]
public partial class tbl_detValija
{
	
	private int _id_detValija;
	
	private System.Nullable<int> _id_cabValija;
	
	private string _sucDestino;
	
	private System.Nullable<int> _departamento;
	
	private string _cedulaEntrega;
	
	private string _numeroGuia;
	
	private string _descripcionEnvio;
	
	private string _descripcionRecibe;
	
	private System.Nullable<bool> _entregado;
	
	public tbl_detValija()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_detValija", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int id_detValija
	{
		get
		{
			return this._id_detValija;
		}
		set
		{
			if ((this._id_detValija != value))
			{
				this._id_detValija = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cabValija", DbType="Int")]
	public System.Nullable<int> id_cabValija
	{
		get
		{
			return this._id_cabValija;
		}
		set
		{
			if ((this._id_cabValija != value))
			{
				this._id_cabValija = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sucDestino", DbType="NChar(3)")]
	public string sucDestino
	{
		get
		{
			return this._sucDestino;
		}
		set
		{
			if ((this._sucDestino != value))
			{
				this._sucDestino = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento", DbType="Int")]
	public System.Nullable<int> departamento
	{
		get
		{
			return this._departamento;
		}
		set
		{
			if ((this._departamento != value))
			{
				this._departamento = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedulaEntrega", DbType="NChar(16)")]
	public string cedulaEntrega
	{
		get
		{
			return this._cedulaEntrega;
		}
		set
		{
			if ((this._cedulaEntrega != value))
			{
				this._cedulaEntrega = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroGuia", DbType="NChar(30)")]
	public string numeroGuia
	{
		get
		{
			return this._numeroGuia;
		}
		set
		{
			if ((this._numeroGuia != value))
			{
				this._numeroGuia = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionEnvio", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string descripcionEnvio
	{
		get
		{
			return this._descripcionEnvio;
		}
		set
		{
			if ((this._descripcionEnvio != value))
			{
				this._descripcionEnvio = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcionRecibe", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string descripcionRecibe
	{
		get
		{
			return this._descripcionRecibe;
		}
		set
		{
			if ((this._descripcionRecibe != value))
			{
				this._descripcionRecibe = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entregado", DbType="Bit")]
	public System.Nullable<bool> entregado
	{
		get
		{
			return this._entregado;
		}
		set
		{
			if ((this._entregado != value))
			{
				this._entregado = value;
			}
		}
	}
}
#pragma warning restore 1591
