#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="temporalrace")]
public partial class // Data_TemporalRaceDataContext: System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void Insertsocios_vehiculos(socios_vehiculos instance);
  partial void Updatesocios_vehiculos(socios_vehiculos instance);
  partial void Deletesocios_vehiculos(socios_vehiculos instance);
  partial void Insertsocios(socios instance);
  partial void Updatesocios(socios instance);
  partial void Deletesocios(socios instance);
  partial void InsertTable_1(Table_1 instance);
  partial void UpdateTable_1(Table_1 instance);
  partial void DeleteTable_1(Table_1 instance);
  #endregion
	
	public Data_TemporalRaceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["temporalraceConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public Data_TemporalRaceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_TemporalRaceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_TemporalRaceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Data_TemporalRaceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<socios_vehiculos> socios_vehiculos
	{
		get
		{
			return this.GetTable<socios_vehiculos>();
		}
	}
	
	public System.Data.Linq.Table<socios> socios
	{
		get
		{
			return this.GetTable<socios>();
		}
	}
	
	public System.Data.Linq.Table<MA_VENDEDOR> MA_VENDEDOR
	{
		get
		{
			return this.GetTable<MA_VENDEDOR>();
		}
	}
	
	public System.Data.Linq.Table<Table_1> Table_1
	{
		get
		{
			return this.GetTable<Table_1>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.socios_vehiculos")]
public partial class socios_vehiculos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _codveh;
	
	private string _factura;
	
	private string _fecini;
	
	private string _marca;
	
	private string _modelo;
	
	private string _ano;
	
	private string _placa;
	
	private string _color;
	
	private string _chasis;
	
	private string _vigmem;
	
	private string _cod_mem;
	
	private string _carmen;
	
	private string _anomem;
	
	private string _contrato;
	
	private decimal _id_veh;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodvehChanging(string value);
    partial void OncodvehChanged();
    partial void OnfacturaChanging(string value);
    partial void OnfacturaChanged();
    partial void OnfeciniChanging(string value);
    partial void OnfeciniChanged();
    partial void OnmarcaChanging(string value);
    partial void OnmarcaChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OnanoChanging(string value);
    partial void OnanoChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OnchasisChanging(string value);
    partial void OnchasisChanged();
    partial void OnvigmemChanging(string value);
    partial void OnvigmemChanged();
    partial void Oncod_memChanging(string value);
    partial void Oncod_memChanged();
    partial void OncarmenChanging(string value);
    partial void OncarmenChanged();
    partial void OnanomemChanging(string value);
    partial void OnanomemChanged();
    partial void OncontratoChanging(string value);
    partial void OncontratoChanged();
    partial void Onid_vehChanging(decimal value);
    partial void Onid_vehChanged();
    #endregion
	
	public socios_vehiculos()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codveh", DbType="NVarChar(50)")]
	public string codveh
	{
		get
		{
			return this._codveh;
		}
		set
		{
			if ((this._codveh != value))
			{
				this.OncodvehChanging(value);
				this.SendPropertyChanging();
				this._codveh = value;
				this.SendPropertyChanged("codveh");
				this.OncodvehChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura", DbType="NVarChar(50)")]
	public string factura
	{
		get
		{
			return this._factura;
		}
		set
		{
			if ((this._factura != value))
			{
				this.OnfacturaChanging(value);
				this.SendPropertyChanging();
				this._factura = value;
				this.SendPropertyChanged("factura");
				this.OnfacturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecini", DbType="NVarChar(50)")]
	public string fecini
	{
		get
		{
			return this._fecini;
		}
		set
		{
			if ((this._fecini != value))
			{
				this.OnfeciniChanging(value);
				this.SendPropertyChanging();
				this._fecini = value;
				this.SendPropertyChanged("fecini");
				this.OnfeciniChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="NVarChar(50)")]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this.OnmarcaChanging(value);
				this.SendPropertyChanging();
				this._marca = value;
				this.SendPropertyChanged("marca");
				this.OnmarcaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="NVarChar(50)")]
	public string modelo
	{
		get
		{
			return this._modelo;
		}
		set
		{
			if ((this._modelo != value))
			{
				this.OnmodeloChanging(value);
				this.SendPropertyChanging();
				this._modelo = value;
				this.SendPropertyChanged("modelo");
				this.OnmodeloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ano", DbType="NVarChar(50)")]
	public string ano
	{
		get
		{
			return this._ano;
		}
		set
		{
			if ((this._ano != value))
			{
				this.OnanoChanging(value);
				this.SendPropertyChanging();
				this._ano = value;
				this.SendPropertyChanged("ano");
				this.OnanoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="NVarChar(50)")]
	public string placa
	{
		get
		{
			return this._placa;
		}
		set
		{
			if ((this._placa != value))
			{
				this.OnplacaChanging(value);
				this.SendPropertyChanging();
				this._placa = value;
				this.SendPropertyChanged("placa");
				this.OnplacaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NVarChar(50)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this.OncolorChanging(value);
				this.SendPropertyChanging();
				this._color = value;
				this.SendPropertyChanged("color");
				this.OncolorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chasis", DbType="NVarChar(50)")]
	public string chasis
	{
		get
		{
			return this._chasis;
		}
		set
		{
			if ((this._chasis != value))
			{
				this.OnchasisChanging(value);
				this.SendPropertyChanging();
				this._chasis = value;
				this.SendPropertyChanged("chasis");
				this.OnchasisChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vigmem", DbType="NVarChar(50)")]
	public string vigmem
	{
		get
		{
			return this._vigmem;
		}
		set
		{
			if ((this._vigmem != value))
			{
				this.OnvigmemChanging(value);
				this.SendPropertyChanging();
				this._vigmem = value;
				this.SendPropertyChanged("vigmem");
				this.OnvigmemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_mem", DbType="NVarChar(50)")]
	public string cod_mem
	{
		get
		{
			return this._cod_mem;
		}
		set
		{
			if ((this._cod_mem != value))
			{
				this.Oncod_memChanging(value);
				this.SendPropertyChanging();
				this._cod_mem = value;
				this.SendPropertyChanged("cod_mem");
				this.Oncod_memChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_carmen", DbType="NVarChar(50)")]
	public string carmen
	{
		get
		{
			return this._carmen;
		}
		set
		{
			if ((this._carmen != value))
			{
				this.OncarmenChanging(value);
				this.SendPropertyChanging();
				this._carmen = value;
				this.SendPropertyChanged("carmen");
				this.OncarmenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anomem", DbType="NVarChar(50)")]
	public string anomem
	{
		get
		{
			return this._anomem;
		}
		set
		{
			if ((this._anomem != value))
			{
				this.OnanomemChanging(value);
				this.SendPropertyChanging();
				this._anomem = value;
				this.SendPropertyChanged("anomem");
				this.OnanomemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrato", DbType="NVarChar(50)")]
	public string contrato
	{
		get
		{
			return this._contrato;
		}
		set
		{
			if ((this._contrato != value))
			{
				this.OncontratoChanging(value);
				this.SendPropertyChanging();
				this._contrato = value;
				this.SendPropertyChanged("contrato");
				this.OncontratoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_veh", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal id_veh
	{
		get
		{
			return this._id_veh;
		}
		set
		{
			if ((this._id_veh != value))
			{
				this.Onid_vehChanging(value);
				this.SendPropertyChanging();
				this._id_veh = value;
				this.SendPropertyChanged("id_veh");
				this.Onid_vehChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.socios")]
public partial class socios : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _ciruc;
	
	private string _apellidos;
	
	private string _nombres;
	
	private string _lugar_nacimiento;
	
	private string _fecha_nacimiento;
	
	private string _estado_civil;
	
	private string _genero;
	
	private string _profesion;
	
	private string _apellido_conyu;
	
	private string _nombre_conyu;
	
	private string _ciudad_domi;
	
	private string _direccion_domi;
	
	private string _sector_domi;
	
	private string _edificio_domi;
	
	private string _piso_domi;
	
	private string _departamento_domi;
	
	private string _referencia_domi;
	
	private string _telefono_contac;
	
	private string _celular_contac;
	
	private string _email_contac;
	
	private string _nombre_empr_trab;
	
	private string _ciudad_trab;
	
	private string _direccion_trab;
	
	private string _sector_trab;
	
	private string _referencia_trab;
	
	private string _telefono_trab;
	
	private string _fax_trab;
	
	private string _email_trab;
	
	private string _marca_vehi;
	
	private string _modelo_vehi;
	
	private string _color_vehi;
	
	private string _placa_vehi;
	
	private string _tipo_for_pag;
	
	private string _banco_for_pag;
	
	private string _ncheque_for_pag;
	
	private string _nombr_tarjet_for_pag;
	
	private string _ntarjeta_for_pag;
	
	private string _plazo_for_pag;
	
	private string _ncontrato_membr;
	
	private string _tipo_membr;
	
	private string _vendedor_membr;
	
	private string _fecha_afiliacion_membr;
	
	private string _fecha_vencimie_membr;
	
	private string _valor_sin_iva;
	
	private string _valor_con_iva;
	
	private string _envio_corresponden;
	
	private decimal _id_nova;
	
	private string _cod_tarjeta;
	
	private string _porfactu;
	
	private string _factura;
	
	private string _cod_suc;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncirucChanging(string value);
    partial void OncirucChanged();
    partial void OnapellidosChanging(string value);
    partial void OnapellidosChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void Onlugar_nacimientoChanging(string value);
    partial void Onlugar_nacimientoChanged();
    partial void Onfecha_nacimientoChanging(string value);
    partial void Onfecha_nacimientoChanged();
    partial void Onestado_civilChanging(string value);
    partial void Onestado_civilChanged();
    partial void OngeneroChanging(string value);
    partial void OngeneroChanged();
    partial void OnprofesionChanging(string value);
    partial void OnprofesionChanged();
    partial void Onapellido_conyuChanging(string value);
    partial void Onapellido_conyuChanged();
    partial void Onnombre_conyuChanging(string value);
    partial void Onnombre_conyuChanged();
    partial void Onciudad_domiChanging(string value);
    partial void Onciudad_domiChanged();
    partial void Ondireccion_domiChanging(string value);
    partial void Ondireccion_domiChanged();
    partial void Onsector_domiChanging(string value);
    partial void Onsector_domiChanged();
    partial void Onedificio_domiChanging(string value);
    partial void Onedificio_domiChanged();
    partial void Onpiso_domiChanging(string value);
    partial void Onpiso_domiChanged();
    partial void Ondepartamento_domiChanging(string value);
    partial void Ondepartamento_domiChanged();
    partial void Onreferencia_domiChanging(string value);
    partial void Onreferencia_domiChanged();
    partial void Ontelefono_contacChanging(string value);
    partial void Ontelefono_contacChanged();
    partial void Oncelular_contacChanging(string value);
    partial void Oncelular_contacChanged();
    partial void Onemail_contacChanging(string value);
    partial void Onemail_contacChanged();
    partial void Onnombre_empr_trabChanging(string value);
    partial void Onnombre_empr_trabChanged();
    partial void Onciudad_trabChanging(string value);
    partial void Onciudad_trabChanged();
    partial void Ondireccion_trabChanging(string value);
    partial void Ondireccion_trabChanged();
    partial void Onsector_trabChanging(string value);
    partial void Onsector_trabChanged();
    partial void Onreferencia_trabChanging(string value);
    partial void Onreferencia_trabChanged();
    partial void Ontelefono_trabChanging(string value);
    partial void Ontelefono_trabChanged();
    partial void Onfax_trabChanging(string value);
    partial void Onfax_trabChanged();
    partial void Onemail_trabChanging(string value);
    partial void Onemail_trabChanged();
    partial void Onmarca_vehiChanging(string value);
    partial void Onmarca_vehiChanged();
    partial void Onmodelo_vehiChanging(string value);
    partial void Onmodelo_vehiChanged();
    partial void Oncolor_vehiChanging(string value);
    partial void Oncolor_vehiChanged();
    partial void Onplaca_vehiChanging(string value);
    partial void Onplaca_vehiChanged();
    partial void Ontipo_for_pagChanging(string value);
    partial void Ontipo_for_pagChanged();
    partial void Onbanco_for_pagChanging(string value);
    partial void Onbanco_for_pagChanged();
    partial void Onncheque_for_pagChanging(string value);
    partial void Onncheque_for_pagChanged();
    partial void Onnombr_tarjet_for_pagChanging(string value);
    partial void Onnombr_tarjet_for_pagChanged();
    partial void Onntarjeta_for_pagChanging(string value);
    partial void Onntarjeta_for_pagChanged();
    partial void Onplazo_for_pagChanging(string value);
    partial void Onplazo_for_pagChanged();
    partial void Onncontrato_membrChanging(string value);
    partial void Onncontrato_membrChanged();
    partial void Ontipo_membrChanging(string value);
    partial void Ontipo_membrChanged();
    partial void Onvendedor_membrChanging(string value);
    partial void Onvendedor_membrChanged();
    partial void Onfecha_afiliacion_membrChanging(string value);
    partial void Onfecha_afiliacion_membrChanged();
    partial void Onfecha_vencimie_membrChanging(string value);
    partial void Onfecha_vencimie_membrChanged();
    partial void Onvalor_sin_ivaChanging(string value);
    partial void Onvalor_sin_ivaChanged();
    partial void Onvalor_con_ivaChanging(string value);
    partial void Onvalor_con_ivaChanged();
    partial void Onenvio_correspondenChanging(string value);
    partial void Onenvio_correspondenChanged();
    partial void Onid_novaChanging(decimal value);
    partial void Onid_novaChanged();
    partial void Oncod_tarjetaChanging(string value);
    partial void Oncod_tarjetaChanged();
    partial void OnporfactuChanging(string value);
    partial void OnporfactuChanged();
    partial void OnfacturaChanging(string value);
    partial void OnfacturaChanged();
    partial void Oncod_sucChanging(string value);
    partial void Oncod_sucChanged();
    #endregion
	
	public socios()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciruc", DbType="VarChar(100)")]
	public string ciruc
	{
		get
		{
			return this._ciruc;
		}
		set
		{
			if ((this._ciruc != value))
			{
				this.OncirucChanging(value);
				this.SendPropertyChanging();
				this._ciruc = value;
				this.SendPropertyChanged("ciruc");
				this.OncirucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellidos", DbType="VarChar(500)")]
	public string apellidos
	{
		get
		{
			return this._apellidos;
		}
		set
		{
			if ((this._apellidos != value))
			{
				this.OnapellidosChanging(value);
				this.SendPropertyChanging();
				this._apellidos = value;
				this.SendPropertyChanged("apellidos");
				this.OnapellidosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="VarChar(500)")]
	public string nombres
	{
		get
		{
			return this._nombres;
		}
		set
		{
			if ((this._nombres != value))
			{
				this.OnnombresChanging(value);
				this.SendPropertyChanging();
				this._nombres = value;
				this.SendPropertyChanged("nombres");
				this.OnnombresChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugar_nacimiento", DbType="VarChar(100)")]
	public string lugar_nacimiento
	{
		get
		{
			return this._lugar_nacimiento;
		}
		set
		{
			if ((this._lugar_nacimiento != value))
			{
				this.Onlugar_nacimientoChanging(value);
				this.SendPropertyChanging();
				this._lugar_nacimiento = value;
				this.SendPropertyChanged("lugar_nacimiento");
				this.Onlugar_nacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="VarChar(100)")]
	public string fecha_nacimiento
	{
		get
		{
			return this._fecha_nacimiento;
		}
		set
		{
			if ((this._fecha_nacimiento != value))
			{
				this.Onfecha_nacimientoChanging(value);
				this.SendPropertyChanging();
				this._fecha_nacimiento = value;
				this.SendPropertyChanged("fecha_nacimiento");
				this.Onfecha_nacimientoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_civil", DbType="VarChar(100)")]
	public string estado_civil
	{
		get
		{
			return this._estado_civil;
		}
		set
		{
			if ((this._estado_civil != value))
			{
				this.Onestado_civilChanging(value);
				this.SendPropertyChanging();
				this._estado_civil = value;
				this.SendPropertyChanged("estado_civil");
				this.Onestado_civilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_genero", DbType="VarChar(100)")]
	public string genero
	{
		get
		{
			return this._genero;
		}
		set
		{
			if ((this._genero != value))
			{
				this.OngeneroChanging(value);
				this.SendPropertyChanging();
				this._genero = value;
				this.SendPropertyChanged("genero");
				this.OngeneroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profesion", DbType="VarChar(100)")]
	public string profesion
	{
		get
		{
			return this._profesion;
		}
		set
		{
			if ((this._profesion != value))
			{
				this.OnprofesionChanging(value);
				this.SendPropertyChanging();
				this._profesion = value;
				this.SendPropertyChanged("profesion");
				this.OnprofesionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_conyu", DbType="VarChar(500)")]
	public string apellido_conyu
	{
		get
		{
			return this._apellido_conyu;
		}
		set
		{
			if ((this._apellido_conyu != value))
			{
				this.Onapellido_conyuChanging(value);
				this.SendPropertyChanging();
				this._apellido_conyu = value;
				this.SendPropertyChanged("apellido_conyu");
				this.Onapellido_conyuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_conyu", DbType="VarChar(500)")]
	public string nombre_conyu
	{
		get
		{
			return this._nombre_conyu;
		}
		set
		{
			if ((this._nombre_conyu != value))
			{
				this.Onnombre_conyuChanging(value);
				this.SendPropertyChanging();
				this._nombre_conyu = value;
				this.SendPropertyChanged("nombre_conyu");
				this.Onnombre_conyuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad_domi", DbType="VarChar(500)")]
	public string ciudad_domi
	{
		get
		{
			return this._ciudad_domi;
		}
		set
		{
			if ((this._ciudad_domi != value))
			{
				this.Onciudad_domiChanging(value);
				this.SendPropertyChanging();
				this._ciudad_domi = value;
				this.SendPropertyChanged("ciudad_domi");
				this.Onciudad_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_domi", DbType="VarChar(500)")]
	public string direccion_domi
	{
		get
		{
			return this._direccion_domi;
		}
		set
		{
			if ((this._direccion_domi != value))
			{
				this.Ondireccion_domiChanging(value);
				this.SendPropertyChanging();
				this._direccion_domi = value;
				this.SendPropertyChanged("direccion_domi");
				this.Ondireccion_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sector_domi", DbType="VarChar(500)")]
	public string sector_domi
	{
		get
		{
			return this._sector_domi;
		}
		set
		{
			if ((this._sector_domi != value))
			{
				this.Onsector_domiChanging(value);
				this.SendPropertyChanging();
				this._sector_domi = value;
				this.SendPropertyChanged("sector_domi");
				this.Onsector_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edificio_domi", DbType="VarChar(500)")]
	public string edificio_domi
	{
		get
		{
			return this._edificio_domi;
		}
		set
		{
			if ((this._edificio_domi != value))
			{
				this.Onedificio_domiChanging(value);
				this.SendPropertyChanging();
				this._edificio_domi = value;
				this.SendPropertyChanged("edificio_domi");
				this.Onedificio_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_piso_domi", DbType="VarChar(100)")]
	public string piso_domi
	{
		get
		{
			return this._piso_domi;
		}
		set
		{
			if ((this._piso_domi != value))
			{
				this.Onpiso_domiChanging(value);
				this.SendPropertyChanging();
				this._piso_domi = value;
				this.SendPropertyChanged("piso_domi");
				this.Onpiso_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departamento_domi", DbType="VarChar(500)")]
	public string departamento_domi
	{
		get
		{
			return this._departamento_domi;
		}
		set
		{
			if ((this._departamento_domi != value))
			{
				this.Ondepartamento_domiChanging(value);
				this.SendPropertyChanging();
				this._departamento_domi = value;
				this.SendPropertyChanged("departamento_domi");
				this.Ondepartamento_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_domi", DbType="VarChar(500)")]
	public string referencia_domi
	{
		get
		{
			return this._referencia_domi;
		}
		set
		{
			if ((this._referencia_domi != value))
			{
				this.Onreferencia_domiChanging(value);
				this.SendPropertyChanging();
				this._referencia_domi = value;
				this.SendPropertyChanged("referencia_domi");
				this.Onreferencia_domiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_contac", DbType="VarChar(100)")]
	public string telefono_contac
	{
		get
		{
			return this._telefono_contac;
		}
		set
		{
			if ((this._telefono_contac != value))
			{
				this.Ontelefono_contacChanging(value);
				this.SendPropertyChanging();
				this._telefono_contac = value;
				this.SendPropertyChanged("telefono_contac");
				this.Ontelefono_contacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular_contac", DbType="VarChar(100)")]
	public string celular_contac
	{
		get
		{
			return this._celular_contac;
		}
		set
		{
			if ((this._celular_contac != value))
			{
				this.Oncelular_contacChanging(value);
				this.SendPropertyChanging();
				this._celular_contac = value;
				this.SendPropertyChanged("celular_contac");
				this.Oncelular_contacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_contac", DbType="VarChar(500)")]
	public string email_contac
	{
		get
		{
			return this._email_contac;
		}
		set
		{
			if ((this._email_contac != value))
			{
				this.Onemail_contacChanging(value);
				this.SendPropertyChanging();
				this._email_contac = value;
				this.SendPropertyChanged("email_contac");
				this.Onemail_contacChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_empr_trab", DbType="VarChar(500)")]
	public string nombre_empr_trab
	{
		get
		{
			return this._nombre_empr_trab;
		}
		set
		{
			if ((this._nombre_empr_trab != value))
			{
				this.Onnombre_empr_trabChanging(value);
				this.SendPropertyChanging();
				this._nombre_empr_trab = value;
				this.SendPropertyChanged("nombre_empr_trab");
				this.Onnombre_empr_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad_trab", DbType="VarChar(500)")]
	public string ciudad_trab
	{
		get
		{
			return this._ciudad_trab;
		}
		set
		{
			if ((this._ciudad_trab != value))
			{
				this.Onciudad_trabChanging(value);
				this.SendPropertyChanging();
				this._ciudad_trab = value;
				this.SendPropertyChanged("ciudad_trab");
				this.Onciudad_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion_trab", DbType="VarChar(500)")]
	public string direccion_trab
	{
		get
		{
			return this._direccion_trab;
		}
		set
		{
			if ((this._direccion_trab != value))
			{
				this.Ondireccion_trabChanging(value);
				this.SendPropertyChanging();
				this._direccion_trab = value;
				this.SendPropertyChanged("direccion_trab");
				this.Ondireccion_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sector_trab", DbType="VarChar(500)")]
	public string sector_trab
	{
		get
		{
			return this._sector_trab;
		}
		set
		{
			if ((this._sector_trab != value))
			{
				this.Onsector_trabChanging(value);
				this.SendPropertyChanging();
				this._sector_trab = value;
				this.SendPropertyChanged("sector_trab");
				this.Onsector_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_trab", DbType="VarChar(500)")]
	public string referencia_trab
	{
		get
		{
			return this._referencia_trab;
		}
		set
		{
			if ((this._referencia_trab != value))
			{
				this.Onreferencia_trabChanging(value);
				this.SendPropertyChanging();
				this._referencia_trab = value;
				this.SendPropertyChanged("referencia_trab");
				this.Onreferencia_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_trab", DbType="VarChar(100)")]
	public string telefono_trab
	{
		get
		{
			return this._telefono_trab;
		}
		set
		{
			if ((this._telefono_trab != value))
			{
				this.Ontelefono_trabChanging(value);
				this.SendPropertyChanging();
				this._telefono_trab = value;
				this.SendPropertyChanged("telefono_trab");
				this.Ontelefono_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax_trab", DbType="VarChar(100)")]
	public string fax_trab
	{
		get
		{
			return this._fax_trab;
		}
		set
		{
			if ((this._fax_trab != value))
			{
				this.Onfax_trabChanging(value);
				this.SendPropertyChanging();
				this._fax_trab = value;
				this.SendPropertyChanged("fax_trab");
				this.Onfax_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_trab", DbType="VarChar(500)")]
	public string email_trab
	{
		get
		{
			return this._email_trab;
		}
		set
		{
			if ((this._email_trab != value))
			{
				this.Onemail_trabChanging(value);
				this.SendPropertyChanging();
				this._email_trab = value;
				this.SendPropertyChanged("email_trab");
				this.Onemail_trabChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca_vehi", DbType="VarChar(100)")]
	public string marca_vehi
	{
		get
		{
			return this._marca_vehi;
		}
		set
		{
			if ((this._marca_vehi != value))
			{
				this.Onmarca_vehiChanging(value);
				this.SendPropertyChanging();
				this._marca_vehi = value;
				this.SendPropertyChanged("marca_vehi");
				this.Onmarca_vehiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo_vehi", DbType="VarChar(100)")]
	public string modelo_vehi
	{
		get
		{
			return this._modelo_vehi;
		}
		set
		{
			if ((this._modelo_vehi != value))
			{
				this.Onmodelo_vehiChanging(value);
				this.SendPropertyChanging();
				this._modelo_vehi = value;
				this.SendPropertyChanged("modelo_vehi");
				this.Onmodelo_vehiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color_vehi", DbType="VarChar(100)")]
	public string color_vehi
	{
		get
		{
			return this._color_vehi;
		}
		set
		{
			if ((this._color_vehi != value))
			{
				this.Oncolor_vehiChanging(value);
				this.SendPropertyChanging();
				this._color_vehi = value;
				this.SendPropertyChanged("color_vehi");
				this.Oncolor_vehiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa_vehi", DbType="VarChar(100)")]
	public string placa_vehi
	{
		get
		{
			return this._placa_vehi;
		}
		set
		{
			if ((this._placa_vehi != value))
			{
				this.Onplaca_vehiChanging(value);
				this.SendPropertyChanging();
				this._placa_vehi = value;
				this.SendPropertyChanged("placa_vehi");
				this.Onplaca_vehiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_for_pag", DbType="VarChar(100)")]
	public string tipo_for_pag
	{
		get
		{
			return this._tipo_for_pag;
		}
		set
		{
			if ((this._tipo_for_pag != value))
			{
				this.Ontipo_for_pagChanging(value);
				this.SendPropertyChanging();
				this._tipo_for_pag = value;
				this.SendPropertyChanged("tipo_for_pag");
				this.Ontipo_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banco_for_pag", DbType="VarChar(100)")]
	public string banco_for_pag
	{
		get
		{
			return this._banco_for_pag;
		}
		set
		{
			if ((this._banco_for_pag != value))
			{
				this.Onbanco_for_pagChanging(value);
				this.SendPropertyChanging();
				this._banco_for_pag = value;
				this.SendPropertyChanged("banco_for_pag");
				this.Onbanco_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncheque_for_pag", DbType="VarChar(100)")]
	public string ncheque_for_pag
	{
		get
		{
			return this._ncheque_for_pag;
		}
		set
		{
			if ((this._ncheque_for_pag != value))
			{
				this.Onncheque_for_pagChanging(value);
				this.SendPropertyChanging();
				this._ncheque_for_pag = value;
				this.SendPropertyChanged("ncheque_for_pag");
				this.Onncheque_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombr_tarjet_for_pag", DbType="VarChar(500)")]
	public string nombr_tarjet_for_pag
	{
		get
		{
			return this._nombr_tarjet_for_pag;
		}
		set
		{
			if ((this._nombr_tarjet_for_pag != value))
			{
				this.Onnombr_tarjet_for_pagChanging(value);
				this.SendPropertyChanging();
				this._nombr_tarjet_for_pag = value;
				this.SendPropertyChanged("nombr_tarjet_for_pag");
				this.Onnombr_tarjet_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntarjeta_for_pag", DbType="VarChar(100)")]
	public string ntarjeta_for_pag
	{
		get
		{
			return this._ntarjeta_for_pag;
		}
		set
		{
			if ((this._ntarjeta_for_pag != value))
			{
				this.Onntarjeta_for_pagChanging(value);
				this.SendPropertyChanging();
				this._ntarjeta_for_pag = value;
				this.SendPropertyChanged("ntarjeta_for_pag");
				this.Onntarjeta_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plazo_for_pag", DbType="VarChar(100)")]
	public string plazo_for_pag
	{
		get
		{
			return this._plazo_for_pag;
		}
		set
		{
			if ((this._plazo_for_pag != value))
			{
				this.Onplazo_for_pagChanging(value);
				this.SendPropertyChanging();
				this._plazo_for_pag = value;
				this.SendPropertyChanged("plazo_for_pag");
				this.Onplazo_for_pagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncontrato_membr", DbType="VarChar(500)")]
	public string ncontrato_membr
	{
		get
		{
			return this._ncontrato_membr;
		}
		set
		{
			if ((this._ncontrato_membr != value))
			{
				this.Onncontrato_membrChanging(value);
				this.SendPropertyChanging();
				this._ncontrato_membr = value;
				this.SendPropertyChanged("ncontrato_membr");
				this.Onncontrato_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_membr", DbType="VarChar(500)")]
	public string tipo_membr
	{
		get
		{
			return this._tipo_membr;
		}
		set
		{
			if ((this._tipo_membr != value))
			{
				this.Ontipo_membrChanging(value);
				this.SendPropertyChanging();
				this._tipo_membr = value;
				this.SendPropertyChanged("tipo_membr");
				this.Ontipo_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor_membr", DbType="VarChar(500)")]
	public string vendedor_membr
	{
		get
		{
			return this._vendedor_membr;
		}
		set
		{
			if ((this._vendedor_membr != value))
			{
				this.Onvendedor_membrChanging(value);
				this.SendPropertyChanging();
				this._vendedor_membr = value;
				this.SendPropertyChanged("vendedor_membr");
				this.Onvendedor_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_afiliacion_membr", DbType="VarChar(500)")]
	public string fecha_afiliacion_membr
	{
		get
		{
			return this._fecha_afiliacion_membr;
		}
		set
		{
			if ((this._fecha_afiliacion_membr != value))
			{
				this.Onfecha_afiliacion_membrChanging(value);
				this.SendPropertyChanging();
				this._fecha_afiliacion_membr = value;
				this.SendPropertyChanged("fecha_afiliacion_membr");
				this.Onfecha_afiliacion_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_vencimie_membr", DbType="VarChar(500)")]
	public string fecha_vencimie_membr
	{
		get
		{
			return this._fecha_vencimie_membr;
		}
		set
		{
			if ((this._fecha_vencimie_membr != value))
			{
				this.Onfecha_vencimie_membrChanging(value);
				this.SendPropertyChanging();
				this._fecha_vencimie_membr = value;
				this.SendPropertyChanged("fecha_vencimie_membr");
				this.Onfecha_vencimie_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_sin_iva", DbType="VarChar(500)")]
	public string valor_sin_iva
	{
		get
		{
			return this._valor_sin_iva;
		}
		set
		{
			if ((this._valor_sin_iva != value))
			{
				this.Onvalor_sin_ivaChanging(value);
				this.SendPropertyChanging();
				this._valor_sin_iva = value;
				this.SendPropertyChanged("valor_sin_iva");
				this.Onvalor_sin_ivaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor_con_iva", DbType="VarChar(500)")]
	public string valor_con_iva
	{
		get
		{
			return this._valor_con_iva;
		}
		set
		{
			if ((this._valor_con_iva != value))
			{
				this.Onvalor_con_ivaChanging(value);
				this.SendPropertyChanging();
				this._valor_con_iva = value;
				this.SendPropertyChanged("valor_con_iva");
				this.Onvalor_con_ivaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_envio_corresponden", DbType="VarChar(500)")]
	public string envio_corresponden
	{
		get
		{
			return this._envio_corresponden;
		}
		set
		{
			if ((this._envio_corresponden != value))
			{
				this.Onenvio_correspondenChanging(value);
				this.SendPropertyChanging();
				this._envio_corresponden = value;
				this.SendPropertyChanged("envio_corresponden");
				this.Onenvio_correspondenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nova", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal id_nova
	{
		get
		{
			return this._id_nova;
		}
		set
		{
			if ((this._id_nova != value))
			{
				this.Onid_novaChanging(value);
				this.SendPropertyChanging();
				this._id_nova = value;
				this.SendPropertyChanged("id_nova");
				this.Onid_novaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_tarjeta", DbType="VarChar(100)")]
	public string cod_tarjeta
	{
		get
		{
			return this._cod_tarjeta;
		}
		set
		{
			if ((this._cod_tarjeta != value))
			{
				this.Oncod_tarjetaChanging(value);
				this.SendPropertyChanging();
				this._cod_tarjeta = value;
				this.SendPropertyChanged("cod_tarjeta");
				this.Oncod_tarjetaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porfactu", DbType="NVarChar(50)")]
	public string porfactu
	{
		get
		{
			return this._porfactu;
		}
		set
		{
			if ((this._porfactu != value))
			{
				this.OnporfactuChanging(value);
				this.SendPropertyChanging();
				this._porfactu = value;
				this.SendPropertyChanged("porfactu");
				this.OnporfactuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factura", DbType="NVarChar(50)")]
	public string factura
	{
		get
		{
			return this._factura;
		}
		set
		{
			if ((this._factura != value))
			{
				this.OnfacturaChanging(value);
				this.SendPropertyChanging();
				this._factura = value;
				this.SendPropertyChanged("factura");
				this.OnfacturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_suc", DbType="NVarChar(50)")]
	public string cod_suc
	{
		get
		{
			return this._cod_suc;
		}
		set
		{
			if ((this._cod_suc != value))
			{
				this.Oncod_sucChanging(value);
				this.SendPropertyChanging();
				this._cod_suc = value;
				this.SendPropertyChanged("cod_suc");
				this.Oncod_sucChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MA_VENDEDOR")]
public partial class MA_VENDEDOR
{
	
	private long _MA_VENDEDORID;
	
	private string _MA_VENDEDOR1;
	
	private string _CEDULA;
	
	private System.Nullable<bool> _ESTADO;
	
	public MA_VENDEDOR()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_VENDEDORID", DbType="BigInt NOT NULL")]
	public long MA_VENDEDORID
	{
		get
		{
			return this._MA_VENDEDORID;
		}
		set
		{
			if ((this._MA_VENDEDORID != value))
			{
				this._MA_VENDEDORID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="MA_VENDEDOR", Storage="_MA_VENDEDOR1", DbType="NVarChar(200)")]
	public string MA_VENDEDOR1
	{
		get
		{
			return this._MA_VENDEDOR1;
		}
		set
		{
			if ((this._MA_VENDEDOR1 != value))
			{
				this._MA_VENDEDOR1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA", DbType="VarChar(15)")]
	public string CEDULA
	{
		get
		{
			return this._CEDULA;
		}
		set
		{
			if ((this._CEDULA != value))
			{
				this._CEDULA = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Bit")]
	public System.Nullable<bool> ESTADO
	{
		get
		{
			return this._ESTADO;
		}
		set
		{
			if ((this._ESTADO != value))
			{
				this._ESTADO = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_1")]
public partial class Table_1 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Nullable<System.DateTime> _fecha;
	
	private System.Nullable<System.DateTime> _horasoliserv;
	
	private string _solicitante;
	
	private string _telefono;
	
	private string _nombresocio;
	
	private string _ciruc;
	
	private string _averia;
	
	private string _tipocontrato;
	
	private string _marca;
	
	private string _modelo;
	
	private string _color;
	
	private string _placas;
	
	private string _lugarembarque;
	
	private string _ciudad;
	
	private string _lugardesembarque;
	
	private string _plataforma;
	
	private string _operador;
	
	private string _ejecutivo;
	
	private string _observaciones;
	
	private int _id;
	
	private string _id_usuario;
	
	private string _anio;
	
	private string _idexp;
	
	private string _realizado;
	
	private string _tarifa;
	
	private System.Nullable<System.DateTime> _localizado;
	
	private System.Nullable<System.DateTime> _terminado;
	
	private string _nfactura;
	
	private string _formacobro;
	
	private System.Nullable<decimal> _valor;
	
	private string _estado;
	
	private string _razon_anula;
	
	private string _observa_adicional;
	
	private string _ncontrato_membr;
	
	private System.Nullable<decimal> _km_salida;
	
	private System.Nullable<decimal> _km_embarque;
	
	private System.Nullable<decimal> _km_desembarque;
	
	private System.Nullable<decimal> _km_entrada;
	
	private System.Nullable<decimal> _km_recorrido;
	
	private System.Nullable<decimal> _km_cobertura;
	
	private System.Nullable<decimal> _id_abaste;
	
	private System.Nullable<System.DateTime> _fech_salida;
	
	private System.Nullable<System.DateTime> _fech_embarque;
	
	private System.Nullable<System.DateTime> _fech_desembarque;
	
	private System.Nullable<System.DateTime> _fech_entrada;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnhorasoliservChanging(System.Nullable<System.DateTime> value);
    partial void OnhorasoliservChanged();
    partial void OnsolicitanteChanging(string value);
    partial void OnsolicitanteChanged();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void OnnombresocioChanging(string value);
    partial void OnnombresocioChanged();
    partial void OncirucChanging(string value);
    partial void OncirucChanged();
    partial void OnaveriaChanging(string value);
    partial void OnaveriaChanged();
    partial void OntipocontratoChanging(string value);
    partial void OntipocontratoChanged();
    partial void OnmarcaChanging(string value);
    partial void OnmarcaChanged();
    partial void OnmodeloChanging(string value);
    partial void OnmodeloChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    partial void OnplacasChanging(string value);
    partial void OnplacasChanged();
    partial void OnlugarembarqueChanging(string value);
    partial void OnlugarembarqueChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnlugardesembarqueChanging(string value);
    partial void OnlugardesembarqueChanged();
    partial void OnplataformaChanging(string value);
    partial void OnplataformaChanged();
    partial void OnoperadorChanging(string value);
    partial void OnoperadorChanged();
    partial void OnejecutivoChanging(string value);
    partial void OnejecutivoChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_usuarioChanging(string value);
    partial void Onid_usuarioChanged();
    partial void OnanioChanging(string value);
    partial void OnanioChanged();
    partial void OnidexpChanging(string value);
    partial void OnidexpChanged();
    partial void OnrealizadoChanging(string value);
    partial void OnrealizadoChanged();
    partial void OntarifaChanging(string value);
    partial void OntarifaChanged();
    partial void OnlocalizadoChanging(System.Nullable<System.DateTime> value);
    partial void OnlocalizadoChanged();
    partial void OnterminadoChanging(System.Nullable<System.DateTime> value);
    partial void OnterminadoChanged();
    partial void OnnfacturaChanging(string value);
    partial void OnnfacturaChanged();
    partial void OnformacobroChanging(string value);
    partial void OnformacobroChanged();
    partial void OnvalorChanging(System.Nullable<decimal> value);
    partial void OnvalorChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void Onrazon_anulaChanging(string value);
    partial void Onrazon_anulaChanged();
    partial void Onobserva_adicionalChanging(string value);
    partial void Onobserva_adicionalChanged();
    partial void Onncontrato_membrChanging(string value);
    partial void Onncontrato_membrChanged();
    partial void Onkm_salidaChanging(System.Nullable<decimal> value);
    partial void Onkm_salidaChanged();
    partial void Onkm_embarqueChanging(System.Nullable<decimal> value);
    partial void Onkm_embarqueChanged();
    partial void Onkm_desembarqueChanging(System.Nullable<decimal> value);
    partial void Onkm_desembarqueChanged();
    partial void Onkm_entradaChanging(System.Nullable<decimal> value);
    partial void Onkm_entradaChanged();
    partial void Onkm_recorridoChanging(System.Nullable<decimal> value);
    partial void Onkm_recorridoChanged();
    partial void Onkm_coberturaChanging(System.Nullable<decimal> value);
    partial void Onkm_coberturaChanged();
    partial void Onid_abasteChanging(System.Nullable<decimal> value);
    partial void Onid_abasteChanged();
    partial void Onfech_salidaChanging(System.Nullable<System.DateTime> value);
    partial void Onfech_salidaChanged();
    partial void Onfech_embarqueChanging(System.Nullable<System.DateTime> value);
    partial void Onfech_embarqueChanged();
    partial void Onfech_desembarqueChanging(System.Nullable<System.DateTime> value);
    partial void Onfech_desembarqueChanged();
    partial void Onfech_entradaChanging(System.Nullable<System.DateTime> value);
    partial void Onfech_entradaChanged();
    #endregion
	
	public Table_1()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
	public System.Nullable<System.DateTime> fecha
	{
		get
		{
			return this._fecha;
		}
		set
		{
			if ((this._fecha != value))
			{
				this.OnfechaChanging(value);
				this.SendPropertyChanging();
				this._fecha = value;
				this.SendPropertyChanged("fecha");
				this.OnfechaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_horasoliserv", DbType="DateTime")]
	public System.Nullable<System.DateTime> horasoliserv
	{
		get
		{
			return this._horasoliserv;
		}
		set
		{
			if ((this._horasoliserv != value))
			{
				this.OnhorasoliservChanging(value);
				this.SendPropertyChanging();
				this._horasoliserv = value;
				this.SendPropertyChanged("horasoliserv");
				this.OnhorasoliservChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_solicitante", DbType="VarChar(500)")]
	public string solicitante
	{
		get
		{
			return this._solicitante;
		}
		set
		{
			if ((this._solicitante != value))
			{
				this.OnsolicitanteChanging(value);
				this.SendPropertyChanging();
				this._solicitante = value;
				this.SendPropertyChanged("solicitante");
				this.OnsolicitanteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(100)")]
	public string telefono
	{
		get
		{
			return this._telefono;
		}
		set
		{
			if ((this._telefono != value))
			{
				this.OntelefonoChanging(value);
				this.SendPropertyChanging();
				this._telefono = value;
				this.SendPropertyChanged("telefono");
				this.OntelefonoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombresocio", DbType="VarChar(1000)")]
	public string nombresocio
	{
		get
		{
			return this._nombresocio;
		}
		set
		{
			if ((this._nombresocio != value))
			{
				this.OnnombresocioChanging(value);
				this.SendPropertyChanging();
				this._nombresocio = value;
				this.SendPropertyChanged("nombresocio");
				this.OnnombresocioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciruc", DbType="VarChar(100)")]
	public string ciruc
	{
		get
		{
			return this._ciruc;
		}
		set
		{
			if ((this._ciruc != value))
			{
				this.OncirucChanging(value);
				this.SendPropertyChanging();
				this._ciruc = value;
				this.SendPropertyChanged("ciruc");
				this.OncirucChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_averia", DbType="VarChar(100)")]
	public string averia
	{
		get
		{
			return this._averia;
		}
		set
		{
			if ((this._averia != value))
			{
				this.OnaveriaChanging(value);
				this.SendPropertyChanging();
				this._averia = value;
				this.SendPropertyChanged("averia");
				this.OnaveriaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipocontrato", DbType="VarChar(100)")]
	public string tipocontrato
	{
		get
		{
			return this._tipocontrato;
		}
		set
		{
			if ((this._tipocontrato != value))
			{
				this.OntipocontratoChanging(value);
				this.SendPropertyChanging();
				this._tipocontrato = value;
				this.SendPropertyChanged("tipocontrato");
				this.OntipocontratoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marca", DbType="VarChar(100)")]
	public string marca
	{
		get
		{
			return this._marca;
		}
		set
		{
			if ((this._marca != value))
			{
				this.OnmarcaChanging(value);
				this.SendPropertyChanging();
				this._marca = value;
				this.SendPropertyChanged("marca");
				this.OnmarcaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modelo", DbType="VarChar(100)")]
	public string modelo
	{
		get
		{
			return this._modelo;
		}
		set
		{
			if ((this._modelo != value))
			{
				this.OnmodeloChanging(value);
				this.SendPropertyChanging();
				this._modelo = value;
				this.SendPropertyChanged("modelo");
				this.OnmodeloChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="VarChar(100)")]
	public string color
	{
		get
		{
			return this._color;
		}
		set
		{
			if ((this._color != value))
			{
				this.OncolorChanging(value);
				this.SendPropertyChanging();
				this._color = value;
				this.SendPropertyChanged("color");
				this.OncolorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placas", DbType="VarChar(100)")]
	public string placas
	{
		get
		{
			return this._placas;
		}
		set
		{
			if ((this._placas != value))
			{
				this.OnplacasChanging(value);
				this.SendPropertyChanging();
				this._placas = value;
				this.SendPropertyChanged("placas");
				this.OnplacasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugarembarque", DbType="VarChar(1000)")]
	public string lugarembarque
	{
		get
		{
			return this._lugarembarque;
		}
		set
		{
			if ((this._lugarembarque != value))
			{
				this.OnlugarembarqueChanging(value);
				this.SendPropertyChanging();
				this._lugarembarque = value;
				this.SendPropertyChanged("lugarembarque");
				this.OnlugarembarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(1000)")]
	public string ciudad
	{
		get
		{
			return this._ciudad;
		}
		set
		{
			if ((this._ciudad != value))
			{
				this.OnciudadChanging(value);
				this.SendPropertyChanging();
				this._ciudad = value;
				this.SendPropertyChanged("ciudad");
				this.OnciudadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lugardesembarque", DbType="VarChar(1000)")]
	public string lugardesembarque
	{
		get
		{
			return this._lugardesembarque;
		}
		set
		{
			if ((this._lugardesembarque != value))
			{
				this.OnlugardesembarqueChanging(value);
				this.SendPropertyChanging();
				this._lugardesembarque = value;
				this.SendPropertyChanged("lugardesembarque");
				this.OnlugardesembarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plataforma", DbType="VarChar(100)")]
	public string plataforma
	{
		get
		{
			return this._plataforma;
		}
		set
		{
			if ((this._plataforma != value))
			{
				this.OnplataformaChanging(value);
				this.SendPropertyChanging();
				this._plataforma = value;
				this.SendPropertyChanged("plataforma");
				this.OnplataformaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operador", DbType="VarChar(100)")]
	public string operador
	{
		get
		{
			return this._operador;
		}
		set
		{
			if ((this._operador != value))
			{
				this.OnoperadorChanging(value);
				this.SendPropertyChanging();
				this._operador = value;
				this.SendPropertyChanged("operador");
				this.OnoperadorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ejecutivo", DbType="VarChar(100)")]
	public string ejecutivo
	{
		get
		{
			return this._ejecutivo;
		}
		set
		{
			if ((this._ejecutivo != value))
			{
				this.OnejecutivoChanging(value);
				this.SendPropertyChanging();
				this._ejecutivo = value;
				this.SendPropertyChanged("ejecutivo");
				this.OnejecutivoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(1000)")]
	public string observaciones
	{
		get
		{
			return this._observaciones;
		}
		set
		{
			if ((this._observaciones != value))
			{
				this.OnobservacionesChanging(value);
				this.SendPropertyChanging();
				this._observaciones = value;
				this.SendPropertyChanged("observaciones");
				this.OnobservacionesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_usuario", DbType="VarChar(100)")]
	public string id_usuario
	{
		get
		{
			return this._id_usuario;
		}
		set
		{
			if ((this._id_usuario != value))
			{
				this.Onid_usuarioChanging(value);
				this.SendPropertyChanging();
				this._id_usuario = value;
				this.SendPropertyChanged("id_usuario");
				this.Onid_usuarioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anio", DbType="VarChar(100)")]
	public string anio
	{
		get
		{
			return this._anio;
		}
		set
		{
			if ((this._anio != value))
			{
				this.OnanioChanging(value);
				this.SendPropertyChanging();
				this._anio = value;
				this.SendPropertyChanged("anio");
				this.OnanioChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idexp", DbType="VarChar(100)")]
	public string idexp
	{
		get
		{
			return this._idexp;
		}
		set
		{
			if ((this._idexp != value))
			{
				this.OnidexpChanging(value);
				this.SendPropertyChanging();
				this._idexp = value;
				this.SendPropertyChanged("idexp");
				this.OnidexpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_realizado", DbType="VarChar(100)")]
	public string realizado
	{
		get
		{
			return this._realizado;
		}
		set
		{
			if ((this._realizado != value))
			{
				this.OnrealizadoChanging(value);
				this.SendPropertyChanging();
				this._realizado = value;
				this.SendPropertyChanged("realizado");
				this.OnrealizadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarifa", DbType="VarChar(100)")]
	public string tarifa
	{
		get
		{
			return this._tarifa;
		}
		set
		{
			if ((this._tarifa != value))
			{
				this.OntarifaChanging(value);
				this.SendPropertyChanging();
				this._tarifa = value;
				this.SendPropertyChanged("tarifa");
				this.OntarifaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_localizado", DbType="DateTime")]
	public System.Nullable<System.DateTime> localizado
	{
		get
		{
			return this._localizado;
		}
		set
		{
			if ((this._localizado != value))
			{
				this.OnlocalizadoChanging(value);
				this.SendPropertyChanging();
				this._localizado = value;
				this.SendPropertyChanged("localizado");
				this.OnlocalizadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_terminado", DbType="DateTime")]
	public System.Nullable<System.DateTime> terminado
	{
		get
		{
			return this._terminado;
		}
		set
		{
			if ((this._terminado != value))
			{
				this.OnterminadoChanging(value);
				this.SendPropertyChanging();
				this._terminado = value;
				this.SendPropertyChanged("terminado");
				this.OnterminadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nfactura", DbType="VarChar(100)")]
	public string nfactura
	{
		get
		{
			return this._nfactura;
		}
		set
		{
			if ((this._nfactura != value))
			{
				this.OnnfacturaChanging(value);
				this.SendPropertyChanging();
				this._nfactura = value;
				this.SendPropertyChanged("nfactura");
				this.OnnfacturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formacobro", DbType="VarChar(100)")]
	public string formacobro
	{
		get
		{
			return this._formacobro;
		}
		set
		{
			if ((this._formacobro != value))
			{
				this.OnformacobroChanging(value);
				this.SendPropertyChanging();
				this._formacobro = value;
				this.SendPropertyChanged("formacobro");
				this.OnformacobroChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> valor
	{
		get
		{
			return this._valor;
		}
		set
		{
			if ((this._valor != value))
			{
				this.OnvalorChanging(value);
				this.SendPropertyChanging();
				this._valor = value;
				this.SendPropertyChanged("valor");
				this.OnvalorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(100)")]
	public string estado
	{
		get
		{
			return this._estado;
		}
		set
		{
			if ((this._estado != value))
			{
				this.OnestadoChanging(value);
				this.SendPropertyChanging();
				this._estado = value;
				this.SendPropertyChanged("estado");
				this.OnestadoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_razon_anula", DbType="VarChar(1000)")]
	public string razon_anula
	{
		get
		{
			return this._razon_anula;
		}
		set
		{
			if ((this._razon_anula != value))
			{
				this.Onrazon_anulaChanging(value);
				this.SendPropertyChanging();
				this._razon_anula = value;
				this.SendPropertyChanged("razon_anula");
				this.Onrazon_anulaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observa_adicional", DbType="VarChar(100)")]
	public string observa_adicional
	{
		get
		{
			return this._observa_adicional;
		}
		set
		{
			if ((this._observa_adicional != value))
			{
				this.Onobserva_adicionalChanging(value);
				this.SendPropertyChanging();
				this._observa_adicional = value;
				this.SendPropertyChanged("observa_adicional");
				this.Onobserva_adicionalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ncontrato_membr", DbType="VarChar(100)")]
	public string ncontrato_membr
	{
		get
		{
			return this._ncontrato_membr;
		}
		set
		{
			if ((this._ncontrato_membr != value))
			{
				this.Onncontrato_membrChanging(value);
				this.SendPropertyChanging();
				this._ncontrato_membr = value;
				this.SendPropertyChanged("ncontrato_membr");
				this.Onncontrato_membrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_salida", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_salida
	{
		get
		{
			return this._km_salida;
		}
		set
		{
			if ((this._km_salida != value))
			{
				this.Onkm_salidaChanging(value);
				this.SendPropertyChanging();
				this._km_salida = value;
				this.SendPropertyChanged("km_salida");
				this.Onkm_salidaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_embarque", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_embarque
	{
		get
		{
			return this._km_embarque;
		}
		set
		{
			if ((this._km_embarque != value))
			{
				this.Onkm_embarqueChanging(value);
				this.SendPropertyChanging();
				this._km_embarque = value;
				this.SendPropertyChanged("km_embarque");
				this.Onkm_embarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_desembarque", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_desembarque
	{
		get
		{
			return this._km_desembarque;
		}
		set
		{
			if ((this._km_desembarque != value))
			{
				this.Onkm_desembarqueChanging(value);
				this.SendPropertyChanging();
				this._km_desembarque = value;
				this.SendPropertyChanged("km_desembarque");
				this.Onkm_desembarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_entrada", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_entrada
	{
		get
		{
			return this._km_entrada;
		}
		set
		{
			if ((this._km_entrada != value))
			{
				this.Onkm_entradaChanging(value);
				this.SendPropertyChanging();
				this._km_entrada = value;
				this.SendPropertyChanged("km_entrada");
				this.Onkm_entradaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_recorrido", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_recorrido
	{
		get
		{
			return this._km_recorrido;
		}
		set
		{
			if ((this._km_recorrido != value))
			{
				this.Onkm_recorridoChanging(value);
				this.SendPropertyChanging();
				this._km_recorrido = value;
				this.SendPropertyChanged("km_recorrido");
				this.Onkm_recorridoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_km_cobertura", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> km_cobertura
	{
		get
		{
			return this._km_cobertura;
		}
		set
		{
			if ((this._km_cobertura != value))
			{
				this.Onkm_coberturaChanging(value);
				this.SendPropertyChanging();
				this._km_cobertura = value;
				this.SendPropertyChanged("km_cobertura");
				this.Onkm_coberturaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_abaste", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> id_abaste
	{
		get
		{
			return this._id_abaste;
		}
		set
		{
			if ((this._id_abaste != value))
			{
				this.Onid_abasteChanging(value);
				this.SendPropertyChanging();
				this._id_abaste = value;
				this.SendPropertyChanged("id_abaste");
				this.Onid_abasteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_salida", DbType="DateTime")]
	public System.Nullable<System.DateTime> fech_salida
	{
		get
		{
			return this._fech_salida;
		}
		set
		{
			if ((this._fech_salida != value))
			{
				this.Onfech_salidaChanging(value);
				this.SendPropertyChanging();
				this._fech_salida = value;
				this.SendPropertyChanged("fech_salida");
				this.Onfech_salidaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_embarque", DbType="DateTime")]
	public System.Nullable<System.DateTime> fech_embarque
	{
		get
		{
			return this._fech_embarque;
		}
		set
		{
			if ((this._fech_embarque != value))
			{
				this.Onfech_embarqueChanging(value);
				this.SendPropertyChanging();
				this._fech_embarque = value;
				this.SendPropertyChanged("fech_embarque");
				this.Onfech_embarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_desembarque", DbType="DateTime")]
	public System.Nullable<System.DateTime> fech_desembarque
	{
		get
		{
			return this._fech_desembarque;
		}
		set
		{
			if ((this._fech_desembarque != value))
			{
				this.Onfech_desembarqueChanging(value);
				this.SendPropertyChanging();
				this._fech_desembarque = value;
				this.SendPropertyChanged("fech_desembarque");
				this.Onfech_desembarqueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fech_entrada", DbType="DateTime")]
	public System.Nullable<System.DateTime> fech_entrada
	{
		get
		{
			return this._fech_entrada;
		}
		set
		{
			if ((this._fech_entrada != value))
			{
				this.Onfech_entradaChanging(value);
				this.SendPropertyChanging();
				this._fech_entrada = value;
				this.SendPropertyChanged("fech_entrada");
				this.Onfech_entradaChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
